Fast api allow file upload + calculation
BenSterenson/finance pull request #44
Opened 2020-08-30 06:19 UTC by BenSterenson

2020-08-30 10:06 UTC, Tzahile requested changes
Please refer to my comments on the `.vue` file.
Off the record, lines 20-27 should be linted.

2020-08-30 10:06 UTC, Tzahile commented on client/src/components/mainContent.vue
> +    this.file = null
That's not the right way using Vue `data()`.
Please read documentation (or watch an example of [single-file-components](https://vuejs.org/v2/guide/single-file-components.html))

2020-08-30 10:06 UTC, Tzahile commented on client/src/components/mainContent.vue
> +            let res = await axios.post("http://127.0.0.1:8000/users/uploadfile/", formData, {"headers" : {'Content-Type': 'multipart/form-data', "Authorization" : `Bearer ${idToken}`},
As we discussed, this `post` request can deliver back the answer that is returned in the `getchange` route.
No need for 2 requests.

2020-08-30 11:47 UTC, MPalarya commented on server/rest_api/routers/users.py
> +raw_data_list: List = []
why is it here? when is this cleared?

2020-08-30 11:53 UTC, MPalarya commented on server/rest_api/routers/users.py
> +    # 6. Run calculations and output results
I think that everything before (6) should go into "upload" API - so that the upload is slow and prepares the data
and the "get" should run faster.
another reason is that multiple "get" requests should not try to re-write things in our dbs or perform calls with maya / yahoo every reload

2020-08-30 11:59 UTC, MPalarya commented on client/src/components/mainContent.vue
> +            let res = await axios.post("http://127.0.0.1:8000/users/uploadfile/", formData, {"headers" : {'Content-Type': 'multipart/form-data', "Authorization" : `Bearer ${idToken}`},
the upload might never happen / happen once or seldom (and takes quite a while to return)
while `get` should be called every time the user logs in or there's a refresh in the data - at least once a day (and should return almost immediately)

I think it's a good idea to keep them separate

2020-08-31 05:58 UTC, BenSterenson commented on server/tests/database/test_mongo_normalized_data_wrapper.py
> +        self.assertEqual(len(bulk_by_user), len(normalized_data_list))
no need to check normalized_data_list fixed

2020-08-31 05:59 UTC, BenSterenson commented on server/tests/database/test_mongo_normalized_data_wrapper.py
> +            item.user_id = user_id
done

2020-08-31 06:00 UTC, BenSterenson commented on client/src/components/mainContent.vue
> +      @click="onFileUpload"
dan will open a new pr with front

2020-08-31 06:01 UTC, BenSterenson commented on client/src/components/mainContent.vue
> +    this.file = null
dan will open a new pr with front

2020-08-31 06:48 UTC, MPalarya approved these changes
LGTM

2020-08-31 06:51 UTC, merged