Vue upload file
BenSterenson/finance pull request #47
Opened 2020-09-05 14:48 UTC by dansterenson

2020-09-14 13:14 UTC, Tzahile requested changes

2020-09-14 13:14 UTC, Tzahile commented on client/src/components/mainContent.vue
> +          multiple
is it correct to have multiple files to upload?

2020-09-14 13:14 UTC, Tzahile commented on client/src/components/mainContent.vue
> +      this.file = [file][0];
should be `this.file = file`

2020-09-14 13:14 UTC, Tzahile commented on client/src/components/mainContent.vue
> +        headers: { "Content-Type": "multipart/form-data", Authorization: `Bearer ${idToken}` },
If we decide not to support multiple files to upload, we should consider removing `multipart/form-data` too

2020-09-14 13:14 UTC, Tzahile commented on client/src/components/mainContent.vue
> +      let res2 = await axios.get("http://127.0.0.1:8000/users/getchange/", {
We don't need to use 2 http requests, while we can receive the `getChange` value in the post request above

2020-09-14 15:51 UTC, BenSterenson commented on client/src/components/mainContent.vue
> +          multiple
i guess we might need to support multiple files in the future

2020-09-14 15:55 UTC, BenSterenson commented on client/src/components/mainContent.vue
> +      let res2 = await axios.get("http://127.0.0.1:8000/users/getchange/", {
@Tzahile we want to break it into two requests since we don't want the user to always upload an excel in order to get the graphs

2020-09-16 16:00 UTC, Tzahile commented on client/src/components/mainContent.vue
> +      let res2 = await axios.get("http://127.0.0.1:8000/users/getchange/", {
I think this is a configuration needs to be made in server.
No problem with a `/GetChange` route, that delivers the same as what `/UploadFile` does

2020-09-16 16:02 UTC, Tzahile commented on client/src/components/mainContent.vue
> +          multiple
I don't know if the client has one or more `.excel` \ `.csv` files to deal with.
If that's the case, do we know how to cope with it?
@MPalarya can you elaborate on this?

2020-09-16 16:10 UTC, dansterenson commented on client/src/components/mainContent.vue
> +      let res2 = await axios.get("http://127.0.0.1:8000/users/getchange/", {
Maybe in the future we will want to support uploading a file without displaying the change, hence I think we should separate them.

2020-09-16 19:18 UTC, dansterenson commented on client/src/components/mainContent.vue
> +      this.file = [file][0];
ok, fixed

2020-09-16 19:28 UTC, Tzahile commented on client/src/components/mainContent.vue
> +      let res2 = await axios.get("http://127.0.0.1:8000/users/getchange/", {
Then we would add it when there's need, it's not a problem.
It is a problem if you add it when it's redundant, especially when it adds unnecessary overhead to your app

2020-09-16 19:35 UTC, MPalarya commented on client/src/components/mainContent.vue
> +          multiple
It's OK to remove the `multiple` file support for now, but we will surely add it one day - see my top commit

One limitation that we should address is the fact that a user cannot manually export his data for a period longer than 1 year in Ordernet-based investing platforms (which are the most common among Israeli independent investors).
So a basic scenario of an investor with a 2+ year portfolio will have to extract the data as multiple files

We should be able to handle this, as we should also support uploading partial files
(i.e. initial `.xls` file when account is created, and a "delta" `.xls` addition every time the user wants to "update")

Right now it is not entirely supported,
- our REST logic will probably ignore any files besides the first one in the list
- our BE logic will probably override the data with the latest file provided instead of aggregating it

2020-09-16 19:35 UTC, MPalarya commented on client/src/components/mainContent.vue
> +      this.file = [file][0];
added to top commit

2020-09-16 19:46 UTC, MPalarya commented on client/src/components/mainContent.vue
> +      let res2 = await axios.get("http://127.0.0.1:8000/users/getchange/", {
I actually think this is best left separated
simple requests with single responsibility -
an "upload" request that does just that, no extra knowledge needed and no implicit logic happening 
if we wanted that, I'd want us to call it "upload_and_get_data" - but it's not a great idea

if we combine them, we will almost certainly decouple them in the -near- future,
but if we leave them separated, I believe that at least the upload's API will remain something like this

I suggest we merge this PR as it is just to be able to build things on top of it
(I know @dansterenson has already added some charts)
we can always re-evaluate when this gets a little bigger

2020-09-16 19:46 UTC, MPalarya commented on client/src/components/mainContent.vue
> +      let res2 = await axios.get("http://127.0.0.1:8000/users/getchange/", {
(also important to note that `upload` will take a pretty long time to return with the calculated data)

2020-09-18 11:27 UTC, MPalarya approved these changes

2020-09-18 11:29 UTC, merged