Displaying charts and shows data if user uploaded it in the past
BenSterenson/finance pull request #54
Opened 2020-09-22 14:34 UTC by dansterenson

2020-09-22 14:53 UTC, BenSterenson approved these changes

2020-09-22 14:53 UTC, BenSterenson commented on client/src/components/mainContent.vue
> +        portfolios = await axios.get("http://127.0.0.1:8000/portfolios/get_portfolios/", {
@dansterenson don't we want to get the url:port from a file?

2020-09-23 09:15 UTC, Tzahile reviewed
I added my review.
Non of the comments is crucial, but preferable to give it a quick-fix

2020-09-23 09:15 UTC, Tzahile commented on client/src/components/mainContent.vue
> +            <table-chart :data-array="this.instrumentsData"></table-chart>
No need for `this` in HTML

2020-09-23 09:15 UTC, Tzahile commented on client/src/components/mainContent.vue
> +        portfolios = await axios.get("/api/portfolios/get_portfolios/", {
Regarding your change in *portfolio.py* file, shouldn't the path be `/api/get_portfolios/`?

2020-09-23 09:15 UTC, Tzahile commented on client/src/components/mainContent.vue
> +      if (res.status === 200) {
Later we will add error handling.
Just for knowledge, I think if the status is erroneous (I think of `4xx & 5xx family`), axios throws an error.
Hence, there's no need to check for status `2xx` (because the if it wasn't, we would've crashed already).

Moreover, in some cases the server might return other `2xx` status codes which are not `200`, and then your if block will be skipped, although result was valid..

2020-09-23 09:25 UTC, BenSterenson commented on client/src/components/mainContent.vue
> +        portfolios = await axios.get("/api/portfolios/get_portfolios/", {
dan is right, it is portfolios/get_portfolios
since the portfolio route is
app.include_router(portfolio.router, prefix="/portfolios", tags=["portfolios"])
@MPalarya maybe we can set it to be only "api/portfolios" what do u think?

2020-09-23 10:03 UTC, MPalarya commented on client/src/components/mainContent.vue
> +        portfolios = await axios.get("/api/portfolios/get_portfolios/", {
I would make it `GET /portfolios`
it's explicit enough - no need in repeating "portfolios" and "GET" in "get_portfolios"
also I don't see a point in including `api` - but I don't mind to keep it if you guys prefer

2020-09-23 10:07 UTC, MPalarya requested changes

2020-09-23 10:07 UTC, MPalarya commented on client/src/components/mainContent.vue
> +      loaded: false,
all of these are pretty bad names
I don't understand what they all represent..

what is loaded?
and since it's a scripting language without type annotations, `loadingPage` can be interpreted as the page that is currently loading...

booleans should really be prefixed with `is / has / should / was`

2020-09-23 19:39 UTC, Tzahile commented on client/src/components/mainContent.vue
> +      loaded: false,
^ Should we reconsider changing to typescript?

2020-09-23 19:41 UTC, Tzahile approved these changes

2020-09-23 19:52 UTC, MPalarya commented on client/src/components/mainContent.vue
> +      loaded: false,
might be a good idea

2020-09-23 20:03 UTC, MPalarya approved these changes

2020-09-23 20:09 UTC, merged