Few minor changes
BenSterenson/finance pull request #56
Opened 2020-09-24 13:30 UTC by dansterenson

Added vue2-highcharts to yarn.lock and package.json
Removed "Vue" icon
Added an alert when no file is uploaded and user clicked "Upload File"

2020-09-24 13:36 UTC, BenSterenson approved these changes

2020-09-25 09:12 UTC, MPalarya requested changes

2020-09-25 09:12 UTC, MPalarya commented on client/src/views/home.vue
> -    <img alt="Vue logo" src="../assets/logo.png" />
the file itself can also be removed

2020-09-25 09:12 UTC, MPalarya commented on client/src/components/mainContent.vue
> +      this.noFileWasChosen = false;
why not use `v-if="!file"`?
if `this.file` is falsy - null/empty/undefined the `if` will render the `<p>`
no need for extra variable and repeated logic

2020-09-25 12:25 UTC, MPalarya approved these changes

2020-09-25 12:33 UTC, merged