Added mock charts to table
BenSterenson/finance pull request #59
Opened 2020-09-24 16:31 UTC by dansterenson

2020-09-24 17:37 UTC, BenSterenson approved these changes

2020-09-25 09:30 UTC, MPalarya commented on client/src/components/charts/tableMockCharts.vue
> +    value: [0, 2, 5, 9, 5, 10, 3, 5, 0, 0, 1, 8, 2, 9, 0],
how about creating a random sequence?
and defining
```
values[-1] > values[0] :: green
values[-1] < values[0] :: red
values[-1] == values[0] :: black/gray

2020-09-25 09:30 UTC, MPalarya commented on client/src/components/charts/tableMockCharts.vue
> +  props: ["isPositive"],
I don't think this should be passed in.. rather calculated as part of this component's logic

2020-09-25 09:30 UTC, MPalarya commented on client/src/components/charts/tableMockCharts.vue
> +      :smooth="radius || false"
isn't this the same as `:smooth="radius"`?

2020-09-25 14:58 UTC, dansterenson commented on client/src/components/charts/tableMockCharts.vue
> +      :smooth="radius || false"
Fixed

2020-09-25 15:01 UTC, dansterenson commented on client/src/components/charts/tableMockCharts.vue
> +  props: ["isPositive"],
Fixed

2020-09-26 09:03 UTC, MPalarya requested changes

2020-09-26 09:03 UTC, MPalarya commented on client/src/components/charts/tableChart.vue
> +      <table-mock-charts is-positive=false>{{ item }}</table-mock-charts>
`is-positive`

2020-09-26 12:11 UTC, dansterenson commented on client/src/components/charts/tableChart.vue
> +      <table-mock-charts is-positive=false>{{ item }}</table-mock-charts>
Fixed

2020-09-26 12:31 UTC, MPalarya approved these changes

2020-09-26 13:43 UTC, merged