Login/SignUp pages design and logic (without Firebase auth)
BenSterenson/finance pull request #70
Opened 2020-10-05 22:39 UTC by dansterenson

2020-10-06 04:09 UTC, BenSterenson approved these changes

2020-10-06 04:39 UTC, BenSterenson requested changes

2020-10-06 04:39 UTC, BenSterenson commented on client/src/views/signin.vue
> +                      src="../../assets/Dark_Network.jpg"
you haven't included this image in pr

2020-10-06 04:39 UTC, BenSterenson commented on client/src/views/signin.vue
> +                        label="   E-MAIL"
why do we have here spaces?

2020-10-06 04:39 UTC, BenSterenson commented on client/src/views/signin.vue
> +                          >DON't HAVE AN ACCOUNT?</v-btn
capital T?

2020-10-06 06:03 UTC, dansterenson commented on client/src/views/signin.vue
> +                        label="   E-MAIL"
I used "yarn run lint --fix" to fix the yarn warnings. I have no idea why it added spaces here. Ill check it

2020-10-06 06:05 UTC, dansterenson commented on client/src/views/signin.vue
> +                          >DON't HAVE AN ACCOUNT?</v-btn
fixed

2020-10-06 06:07 UTC, dansterenson commented on client/src/views/signin.vue
> +                      src="../../assets/Dark_Network.jpg"
right, fixed

2020-10-06 06:41 UTC, BenSterenson approved these changes

2020-10-06 16:17 UTC, MPalarya requested changes

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +            <v-window-item :value="1">
remove `:`

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +      <v-col cols="12" sm="8" md="8">
what happens if you simply don't include `cols`?
let's focus only on large resolutions for now, we won't be able to fit all devices on first attempt

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +      <v-col cols="12" sm="8" md="8">
cols="auto" should work if emitting it keeps it aligned left

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +                      height="700"
can we do 100% instead?

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +                <v-col cols="16" md="6">
this is awfully wrong
every row has 12 spaces
if you are out of them, u need a new row

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +                          label="Remmember me"
remmmmember

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +                          style="font-size: 90%"
this is unusual, should normally be in `px`.. button size shouldn't vary much

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +                            resetError();
create a function for it,
also - what's `step`? why does it inc by 2?

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
>  </template>
this file is a bit too long and how to follow, how about splitting it to smaller components?

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +      signUpPassword2: "",
why 2?

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +      signUpEmail: undefined,
why not use only `email` for both?
if I signup with an email X, I would probably use the same email to login - this will reduce user typing

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +      resetPassEmail: undefined,
ditto

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +      show2: false,
?

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +      selectedCheckBox: undefined,
what checkbx?

2020-10-06 16:17 UTC, MPalarya commented on client/src/views/signin.vue
> +        required: (value) => !!value || "Required.",
this is a bit odd..
`!!value` turns `value` into a boolean
so `required` will return `True` or "Required."?

2020-10-07 09:25 UTC, dansterenson commented on client/yarn.lock
> +vue-material-design-icons@^4.9.0:
We dont need fontawesome and vue-material-design-icons. material-design-icons-iconfont is necessary for vuetify checkbox

2020-10-07 09:32 UTC, dansterenson commented on client/src/apis/firebase.js
> +    await firebase.auth.setPersistence(persistence.SESSION);
If no user is signed in and no persistence is specified, the default setting will be applied (local in a browser app).

2020-10-07 09:33 UTC, dansterenson commented on client/src/apis/firebase.js
> +    return true;
fixed

2020-10-07 09:33 UTC, dansterenson commented on client/src/apis/firebase.js
>      return true;
fixed

2020-10-07 09:35 UTC, dansterenson commented on client/src/apis/firebase.js
> +import firebase, { persistence } from "../firebase.js";
fixed

2020-10-07 09:50 UTC, dansterenson commented on client/src/views/signin.vue
> +      show2: false,
"eye" icon next to password to reveal the password. changed it to showPassword1 and showPassword2.

2020-10-07 09:50 UTC, dansterenson commented on client/src/views/signin.vue
> +      selectedCheckBox: undefined,
removed

2020-10-07 09:59 UTC, dansterenson commented on client/src/views/signin.vue
> +        required: (value) => !!value || "Required.",
It means, if there is no value typed, show "Required." If there is, than change value and dont write "Required.". I took it from stackoverflow, and its working :)

2020-10-07 10:57 UTC, dansterenson commented on client/src/apis/firebase.js
> +    await firebase.auth.setPersistence(persistence.SESSION);
fixed

2020-10-07 22:05 UTC, dansterenson commented on client/src/views/signin.vue
> +      signUpEmail: undefined,
I separated this component to several different components so now each one of them has its own email address.

2020-10-07 22:07 UTC, dansterenson commented on client/src/apis/firebase.js
> +    throw error.message;
fixed

2020-10-07 22:10 UTC, dansterenson commented on client/src/app.vue
> +  <v-app v-bind:style="{ background: activeColor }">
Sometimes its easier like that. if there several rules I can create a CSS section.

2020-10-07 22:14 UTC, dansterenson commented on client/src/app.vue
> +      activeColor: "#151515",
I want the top bar to appear anywhere except the registration page.

2020-10-07 22:14 UTC, dansterenson commented on client/src/app.vue
> +      return this.$route.name === "signin" || this.$route.name === "signup";
fixed

2020-10-07 22:19 UTC, dansterenson commented on client/src/components/navBar.vue
> +      route: this.$route,
removed router

2020-10-07 22:25 UTC, dansterenson commented on client/src/views/signin.vue
> +            <v-window-item :value="1">
It is a shortcut for v-bind:value="1"

2020-10-07 22:27 UTC, dansterenson commented on client/src/views/signin.vue
> +                      height="700"
Yes, fixed

2020-10-07 22:28 UTC, dansterenson commented on client/src/views/signin.vue
> +                          label="Remmember me"
:)

2020-10-07 22:31 UTC, dansterenson commented on client/src/views/signin.vue
> +                          style="font-size: 90%"
fixed

2020-10-07 22:32 UTC, dansterenson commented on client/src/views/signin.vue
> +                            resetError();
Step is to which window to jump when pressing the button. I created a function for that now.

2020-10-07 22:38 UTC, dansterenson commented on client/src/views/signin.vue
> +      signUpPassword2: "",
One for signing up and one for confirming the first one. I changed their names

2020-10-08 10:09 UTC, dansterenson commented on client/src/components/navBar.vue
> +      route: this.$route,
Apparently it does not work if I don't do it like that.

2020-10-09 18:04 UTC, MPalarya commented on client/src/views/registration_windows/resetPassword.vue
> +                isResetSuccess === true ? updateStep(1) : null;
doesn't it make more sense to..?
```javascript
if (isResetSuccess)
    updateStep(1)
```

2020-10-11 09:48 UTC, dansterenson commented on client/yarn.lock
> +vue-material-design-icons@^4.9.0:
fixed

2020-10-11 09:50 UTC, dansterenson commented on client/src/apis/firebase.js
> +    throw error.message;
done

2020-10-11 12:07 UTC, dansterenson commented on client/src/app.vue
> +  <v-app v-bind:style="{ background: activeColor }">
fixed

2020-10-11 12:08 UTC, dansterenson commented on client/src/app.vue
> +      activeColor: "#151515",
fixed

2020-10-11 12:16 UTC, dansterenson commented on client/src/components/navBar.vue
> +      route: this.$route,
fixed

2020-10-14 20:48 UTC, Tzahile commented on client/src/views/signin.vue
> +                          >DON't HAVE AN ACCOUNT?</v-btn
I think `v-btn` makes letters upper-cased by default

2020-10-14 20:57 UTC, Tzahile commented on client/src/views/registration_windows/verifyMail.vue
> +  name: "verifyMail",
https://vuejs.org/v2/api/#name
Not needed unless the component is used recursively, but anyway it's a good practice :)

2020-10-14 21:00 UTC, Tzahile commented on client/src/views/registration_windows/resetPassword.vue
> +                isResetSuccess === true ? updateStep(1) : null;
You can't have an `if` statement in the html area.
Better to take the whole event of this `click` and put it in a method, having more than one statement makes it already packed.

2020-10-14 21:00 UTC, dansterenson commented on client/src/views/registration_windows/verifyMail.vue
> +  name: "verifyMail",
cool, I removed the name

2020-10-14 21:03 UTC, dansterenson commented on client/src/views/signin.vue
> +                          >DON't HAVE AN ACCOUNT?</v-btn
You are right

2020-10-14 21:03 UTC, Tzahile commented on client/src/views/registration_windows/verifyMail.vue
> +  name: "verifyMail",
> ... but anyway it's a good practice

:stuck_out_tongue:

2020-10-17 14:03 UTC, MPalarya approved these changes

2020-10-17 14:03 UTC, MPalarya commented on client/src/views/registration_windows/login.vue
> +              @click="$emit('new-view', views.resetPasswordView)"
:+1:

2020-10-17 14:12 UTC, merged